<a href="https://colab.research.google.com/github/prajaktadhawale/ML-in-marketing/blob/main/Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [31]:

pd.options.mode.chained_assignment = None  # default='warn'

In [32]:
df_training = pd.read_csv("https://raw.githubusercontent.com/miltondavila/datasets/main/iris_training.csv")
df_training

sepal_length  sepal_width  petal_length  petal_width  species
0             6.4          2.8           5.6          2.2        2
1             5.0          2.3           3.3          1.0        1
2             4.9          2.5           4.5          1.7        2
3             4.9          3.1           1.5          0.1        0
4             5.7          3.8           1.7          0.3        0
..            ...          ...           ...          ...      ...
115           5.5          2.6           4.4          1.2        1
116           5.7          3.0           4.2          1.2        1
117           4.4          2.9           1.4          0.2        0
118           4.8          3.0           1.4          0.1        0
119           5.5          2.4           3.7          1.0        1

[120 rows x 5 columns]

In [33]:
# Make sure data types are correct (no objects)
df_training.dtypes # convert in assignment

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int64
dtype: object

In [34]:
# Pop label
target = df_training.pop('species')

In [35]:
# Define features

numeric_feature_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
numeric_features = df_training[numeric_feature_names]
numeric_features.head()

sepal_length  sepal_width  petal_length  petal_width
0           6.4          2.8           5.6          2.2
1           5.0          2.3           3.3          1.0
2           4.9          2.5           4.5          1.7
3           4.9          3.1           1.5          0.1
4           5.7          3.8           1.7          0.3

In [36]:
# Convert data to Tensorflow tensor

numeric_features = tf.convert_to_tensor(numeric_features)
numeric_features

<tf.Tensor: shape=(120, 4), dtype=float64, numpy=
array([[6.4, 2.8, 5.6, 2.2],
       [5. , 2.3, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 3.8, 1.7, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [6.9, 3.1, 5.1, 2.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.1, 3.7, 1.5, 0.4],
       [5.2, 2.7, 3.9, 1.4],
       [6.9, 3.1, 4.9, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [7.7, 3.8, 6.7, 2.2],
       [6.3, 3.3, 4.7, 1.6],
       [6.8, 3.2, 5.9, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [6.4, 3.2, 5.3, 2.3],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.3, 5.7, 2.1],
       [6.4, 2.8, 5.6, 2.1],
       [5.4, 3.9, 1.3, 0.4],
       [6.1, 2.6, 5.6, 1.4],
       [7.2, 3. , 5.8, 1.6],
       [5.2, 3.5, 1.5, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [5.9, 3. , 5.1, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [6.7, 3. , 5. , 1.7],
       [6.3, 2.3, 4.4, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [6.4, 3.2, 4.5,

In [37]:
# Normalize data

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(numeric_features)

In [38]:
# Define the model

def get_basic_model():
  model = tf.keras.Sequential([
    normalizer,
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3) # Possible labels 0, 1 or 2
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                # loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [50]:
# Train model

BATCH_SIZE = 128

model = get_basic_model()
model.fit(numeric_features, target, epochs=500, batch_size=BATCH_SIZE)
#output is affected according to number of epochs, experiment with it
#accuracy should be maximum with loss minimum
#balance the two

Epoch 1/500
1/1 [==============================] - 1s 682ms/step - loss: 1.2046 - accuracy: 0.2917
Epoch 2/500
1/1 [==============================] - 0s 9ms/step - loss: 1.1969 - accuracy: 0.2833
Epoch 3/500
1/1 [==============================] - 0s 12ms/step - loss: 1.1892 - accuracy: 0.2833
Epoch 4/500
1/1 [==============================] - 0s 18ms/step - loss: 1.1817 - accuracy: 0.2833
Epoch 5/500
1/1 [==============================] - 0s 14ms/step - loss: 1.1742 - accuracy: 0.2750
Epoch 6/500
1/1 [==============================] - 0s 10ms/step - loss: 1.1668 - accuracy: 0.2750
Epoch 7/500
1/1 [==============================] - 0s 11ms/step - loss: 1.1595 - accuracy: 0.2583
Epoch 8/500
1/1 [==============================] - 0s 12ms/step - loss: 1.1522 - accuracy: 0.2500
Epoch 9/500
1/1 [==============================] - 0s 11ms/step - loss: 1.1451 - accuracy: 0.2333
Epoch 10/500
1/1 [==============================] - 0s 18ms/step - loss: 1.1381 - accuracy: 0.2083
Epoch 11/500
1/1 [=

In [51]:

# Download test data

df_test = pd.read_csv("https://raw.githubusercontent.com/miltondavila/datasets/main/iris_test.csv")
df_test.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.9          3.0           4.2          1.5        1
1           6.9          3.1           5.4          2.1        2
2           5.1          3.3           1.7          0.5        0
3           6.0          3.4           4.5          1.6        1
4           5.5          2.5           4.0          1.3        1

In [52]:
# Pop label
test_target = df_test.pop('species')

In [53]:
# Define test features

test_numeric_feature_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
test_numeric_features = df_test[test_numeric_feature_names]
test_numeric_features.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.9          3.0           4.2          1.5
1           6.9          3.1           5.4          2.1
2           5.1          3.3           1.7          0.5
3           6.0          3.4           4.5          1.6
4           5.5          2.5           4.0          1.3

In [54]:
# Convert test data to Tensorflow tensor

test_numeric_features = tf.convert_to_tensor(test_numeric_features)
test_numeric_features

<tf.Tensor: shape=(30, 4), dtype=float64, numpy=
array([[5.9, 3. , 4.2, 1.5],
       [6.9, 3.1, 5.4, 2.1],
       [5.1, 3.3, 1.7, 0.5],
       [6. , 3.4, 4.5, 1.6],
       [5.5, 2.5, 4. , 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [6.3, 2.8, 5.1, 1.5],
       [5.6, 3. , 4.1, 1.3],
       [6.7, 2.5, 5.8, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [4.3, 3. , 1.1, 0.1],
       [5.6, 2.8, 4.9, 2. ],
       [5.5, 2.3, 4. , 1.3],
       [6. , 2.2, 4. , 1. ],
       [5.1, 3.5, 1.4, 0.2],
       [5.7, 2.6, 3.5, 1. ],
       [4.8, 3.4, 1.9, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [5.4, 3.4, 1.7, 0.2],
       [5.6, 3. , 4.5, 1.5],
       [6.3, 2.9, 5.6, 1.8],
       [6.3, 2.5, 4.9, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.2, 4.1, 1.5, 0.1],
       [6.7, 3.1, 4.7, 1.5],
       [6.7, 3.3, 5.7, 2.5],
       [6.4, 2.9, 4.3, 1.3]])>

In [55]:
# Normalize data

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(test_numeric_features)

In [56]:
# Evaluate test data based on training data

score = model.evaluate(test_numeric_features, test_target, verbose=1)
print(f'Test loss: {score[0]} / Test accuracy: {score[1]}')

1/1 [==============================] - 0s 228ms/step - loss: 0.0756 - accuracy: 0.9667
Test loss: 0.0756378322839737 / Test accuracy: 0.9666666388511658


In [57]:

# Save model (optional)

model.save('iris_model')

In [58]:
# Download cases to be predicted

df_predict = pd.read_csv("https://raw.githubusercontent.com/miltondavila/datasets/main/iris_predict.csv")
df_predict

sepal_length  sepal_width  petal_length  petal_width
0           6.0          3.1           4.1          1.6
1           6.7          3.2           5.3          2.0
2           5.1          3.3           1.6          0.4

In [59]:

# Make sure data types are correct (no objects)
# convert it into floats
df_predict.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
dtype: object

In [60]:
# Convert data to Tensorflow tensor

predict_numeric_features = tf.convert_to_tensor(df_predict)
predict_numeric_features

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[6. , 3.1, 4.1, 1.6],
       [6.7, 3.2, 5.3, 2. ],
       [5.1, 3.3, 1.6, 0.4]])>

In [61]:
# Normalize

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(predict_numeric_features)

In [62]:
# Predict labels

class_names = ['Setosa', 'Virginica', 'Versicolor']

predictions = model(predict_numeric_features, training=False)

# Create new columns in dataframe
df_predict['label'] = None
df_predict['certainty'] = None

for i, logits in enumerate(predictions):
  class_idx = tf.argmax(logits).numpy()
  p = tf.nn.softmax(logits)[class_idx]
  name = class_names[class_idx]
  print("Example {} prediction: {} ({:4.1f}%)".format(i, name, 100*p))

  # Save predictions to dataframe
  df_predict["label"].iloc[i] = name
  df_predict['certainty'].iloc[i] = format(p)

Example 0 prediction: Virginica (94.3%)
Example 1 prediction: Versicolor (93.4%)
Example 2 prediction: Setosa (98.8%)


In [63]:
df_predict

sepal_length  sepal_width  petal_length  petal_width       label  \
0           6.0          3.1           4.1          1.6   Virginica   
1           6.7          3.2           5.3          2.0  Versicolor   
2           5.1          3.3           1.6          0.4      Setosa   

            certainty  
0  0.9428125619888306  
1  0.9339528679847717  
2  0.9883841276168823